In [1]:
import pandas as pd
import numpy as np

In [2]:
cond1_column = 'order_amount'
cond2_column = 'num_instalments_initial'
cond1 = 1300
cond2 = 18
violation_column_name = 'rule_violated'

In [6]:
def apply_rules(df, violation_column_name, cond1_column: str, cond1: int, cond2_column: str, cond2: int):
    # Apply the rule: if amount > 1300, number_of_payments must be >= 18, otherwise reject (assign target = 0)
    df[violation_column_name] = np.where((df[cond1_column] > cond1) & (df[cond2_column] < cond2), 1, 0)
    df.loc[df[violation_column_name] == 1, 'target'] = 0  # Assuming rejected applications are non-fraudulent
    return df

In [4]:
# load dataset
df = pd.read_pickle("prueba_tecnica_2023.pkl", compression="bz2")
# dimensionality
print(df.shape)
# check first rows of the dataframe
df.head()

(30000, 65)

,created,order_amount,downpayment_amount,principal_amount,num_instalments_initial,test_ab_version,customer,scheduled_first_payment_date,pm_card_expiration_year,pm_card_expiration_monht,...,ip_userType,ip_reputation,log_providerA_score,ip_address.traits.user_type,providerY_score,payment_method_card_type,bank_countrycode,creditcard_level,creditcard_type,birthday_year
0,2020-09-04,208.00,9.904286,198.095714,20.0,B,cc888cc43ff54eb98cb4f41373f6f606,2020-10-02,NaN,NaN,...,wifi,1.0,-2.302585,cellular,4.0,NaN,NaN,NaN,NaN,2000
1,2020-10-02,34.19,2.180000,32.010000,16.0,B,996046636e2145b8958813e7c9645bb8,2020-11-05,2022.0,12.0,...,wifi,1.0,-2.302585,residential,2.0,visa,ES,CLASSIC,DEBIT,1982
2,2020-12-11,500.77,22.480000,478.290000,24.0,B,8bf9a03537674050a60073279152b8a2,2021-01-10,2024.0,12.0,...,wired,1.0,-1.347074,residential,4.0,visa,ES,ELECTRON,DEBIT,1994
3,2020-11-30,184.95,11.750000,173.200000,16.0,B,3b905c533e034332a61f83933fa11f80,2020-12-28,NaN,NaN,...,wifi,1.0,-2.302585,residential,4.0,NaN,NaN,NaN,NaN,1981
4,2020-09-18,1201.24,53.910000,1147.330000,24.0,B,2d7ea31da4864854997abb5fcd623a06,2020-10-17,2023.0,3.0,...,wifi,1.0,2.600465,residential,5.0,visa,ES,ELECTRON,DEBIT,1997

In [7]:
# apply custom rule
df = apply_rules(df,violation_column_name, cond1_column, cond1, cond2_column, cond2)

In [8]:
# checking if the function works
df['rule_violated'].value_counts()

0    29014
1      986
Name: rule_violated, dtype: int64